### ISSUE TITLE
prix des tickets

### ISSUE THREAD

**Issue by vqoph** [Mutualab/mutualab.org#23]
il y a une erreur sur le prix des tickets sur le site :
il faut modifier le fichier [contents/pricing.json](https://github.com/Mutualab/mutualab.org/blob/master/contents/pricings.json) avec les bons tarifs 

ou me communiquer le bon tarif

**Comment by alexbonhomme** [comment]
Je confirme, je viens de le constater aujourd'hui. Le pack de 20 tickets n'est pas au bon prix (ça devrait être 180e je pense, à vu de nez)

@FlorianeCwl ?
